project_id = "otjnaalbstgxoodczqak"

[functions.career-coach-chat]
verify_jwt = false

[functions.cv-improve-text]
verify_jwt = false

[functions.cv-generate-suggestions]
verify_jwt = false

[functions.interview-analyze-response]
verify_jwt = false

[functions.interview-generate-questions]
verify_jwt = false